version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: trip-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"  # <-- exposed as 5000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: trip-nginx
    ports:
      - "8080:80"  # <--- accessible from http://localhost:8080
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf  # Update this line to the correct file path
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
